# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Left/Right block"
  description: Left/Right content block
  icon: side_navigation
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  data:
    heading: bookshop:generic/component-heading
    content: 
    buttons:
      - label:
    icons: [bookshop:generic/labelled-icon]
  styles:
    orientation:
    image:


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  data:
    heading:
      bookshop: generic/component-heading
      eyebrow_headline: Let your features shine
      primary_heading: A featured icons left right block
    content: Content
    buttons:
      - label: Test button
    icons:
      - bookshop: generic/labelled-icon
        arrangement: stacked
        text: Icon text
        icon:
          bookshop: generic/icon
          svg_icon: solid/academic-cap
          icon_size: small
          rounded_border: true
  styles:
    orientation: Left
    image: http://placekitten.com/500/500

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  orientation:
    type: select
    options:
      values:
        - Left
        - Right  
  content:
    type: markdown