# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Hero"
  description: Provide concise information at the top of the page to engage website visitors
  icon: feed
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    heading: bookshop:generic/component-heading!
    description: Description text to compliment the block
    button: bookshop:generic/button!
    image: bookshop:generic/image!
  styles:
    image_alignment: left
    background_variant: light


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  styles:
    image_alignment: left
    background_variant: light
  content:
    heading:
      _bookshop_name: generic/component-heading
      eyebrow_headline: a small business template
      primary_heading: Empower Your Business with This Brilliant Template
    button:
      url: "#"
      open_in_new_tab: false
      text: Primary
      variant: primary
      disabled: false
      arrow: right
      onclick: console.log(this)
    description: "We wanted you to have a couple of options to use above the fold, and give you the customisation you need to display your product/service in the best way possible."
    image:
      _bookshop_name: generic/image
      image_path: /assets/images/Testimonial--background-feature.png
      image_alt: A woman laughing

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_alignment:
    type: select
    options:
      values:
        - left
        - right
        - full-background
  background_variant:
    comment: This is not used for the full-background image alignment
