# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Icon"
  description: A icon (from https://heroicons.com/) with an optional border and customisable color
  icon: bolt
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  svg_icon: outline/puzzle-piece
  icon_size: small
  rounded_border: false
  color: '#111'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  color:
    comment: This controls the icon color and the rounded border color (if one is included)
  icon_size:
    type: choice
    options:
      values:
        - small
        - large
  svg_icon:
    comment: Visit https://heroicons.com/ to see the full library
    type: select
    options:
      values:
        - solid/academic-cap
        - solid/adjustments-horizontal
        - solid/adjustments-vertical
        - solid/archive-box-arrow-down
        - solid/archive-box-x-mark
        - solid/archive-box
        - solid/arrow-down-circle
        - solid/arrow-down-left
        - solid/arrow-down-on-square-stack
        - solid/arrow-down-on-square
        - solid/arrow-down-right
        - solid/arrow-down-tray
        - solid/arrow-down
        - solid/arrow-left-circle
        - solid/arrow-left-on-rectangle
        - solid/arrow-left
        - solid/arrow-long-down
        - solid/arrow-long-left
        - solid/arrow-long-right
        - solid/arrow-long-up
        - solid/arrow-path-rounded-square
        - solid/arrow-path
        - solid/arrow-right-circle
        - solid/arrow-right-on-rectangle
        - solid/arrow-right
        - solid/arrow-small-down
        - solid/arrow-small-left
        - solid/arrow-small-right
        - solid/arrow-small-up
        - solid/arrow-top-right-on-square
        - solid/arrow-trending-down
        - solid/arrow-trending-up
        - solid/arrow-up-circle
        - solid/arrow-up-left
        - solid/arrow-up-on-square-stack
        - solid/arrow-up-on-square
        - solid/arrow-up-right
        - solid/arrow-up-tray
        - solid/arrow-up
        - solid/arrow-uturn-down
        - solid/arrow-uturn-left
        - solid/arrow-uturn-right
        - solid/arrow-uturn-up
        - solid/arrows-pointing-in
        - solid/arrows-pointing-out
        - solid/arrows-right-left
        - solid/arrows-up-down
        - solid/at-symbol
        - solid/backspace
        - solid/backward
        - solid/banknotes
        - solid/bars-2
        - solid/bars-3-bottom-left
        - solid/bars-3-bottom-right
        - solid/bars-3-center-left
        - solid/bars-3
        - solid/bars-4
        - solid/bars-arrow-down
        - solid/bars-arrow-up
        - solid/battery-0
        - solid/battery-100
        - solid/battery-50
        - solid/beaker
        - solid/bell-alert
        - solid/bell-slash
        - solid/bell-snooze
        - solid/bell
        - solid/bolt-slash
        - solid/bolt
        - solid/book-open
        - solid/bookmark-slash
        - solid/bookmark-square
        - solid/bookmark
        - solid/briefcase
        - solid/bug-ant
        - solid/building-library
        - solid/building-office-2
        - solid/building-office
        - solid/building-storefront
        - solid/cake
        - solid/calculator
        - solid/calendar-days
        - solid/calendar
        - solid/camera
        - solid/chart-bar-square
        - solid/chart-bar
        - solid/chart-pie
        - solid/chat-bubble-bottom-center-text
        - solid/chat-bubble-bottom-center
        - solid/chat-bubble-left-ellipsis
        - solid/chat-bubble-left-right
        - solid/chat-bubble-left
        - solid/chat-bubble-oval-left-ellipsis
        - solid/chat-bubble-oval-left
        - solid/check-badge
        - solid/check-circle
        - solid/check
        - solid/chevron-double-down
        - solid/chevron-double-left
        - solid/chevron-double-right
        - solid/chevron-double-up
        - solid/chevron-down
        - solid/chevron-left
        - solid/chevron-right
        - solid/chevron-up-down
        - solid/chevron-up
        - solid/circle-stack
        - solid/clipboard-document-check
        - solid/clipboard-document-list
        - solid/clipboard-document
        - solid/clipboard
        - solid/clock
        - solid/cloud-arrow-down
        - solid/cloud-arrow-up
        - solid/cloud
        - solid/code-bracket-square
        - solid/code-bracket
        - solid/cog-6-tooth
        - solid/cog-8-tooth
        - solid/cog
        - solid/command-line
        - solid/computer-desktop
        - solid/cpu-chip
        - solid/credit-card
        - solid/cube-transparent
        - solid/cube
        - solid/currency-bangladeshi
        - solid/currency-dollar
        - solid/currency-euro
        - solid/currency-pound
        - solid/currency-rupee
        - solid/currency-yen
        - solid/cursor-arrow-rays
        - solid/cursor-arrow-ripple
        - solid/device-phone-mobile
        - solid/device-tablet
        - solid/document-arrow-down
        - solid/document-arrow-up
        - solid/document-chart-bar
        - solid/document-check
        - solid/document-duplicate
        - solid/document-magnifying-glass
        - solid/document-minus
        - solid/document-plus
        - solid/document-text
        - solid/document
        - solid/ellipsis-horizontal-circle
        - solid/ellipsis-horizontal
        - solid/ellipsis-vertical
        - solid/envelope-open
        - solid/envelope
        - solid/exclamation-circle
        - solid/exclamation-triangle
        - solid/eye-dropper
        - solid/eye-slash
        - solid/eye
        - solid/face-frown
        - solid/face-smile
        - solid/film
        - solid/finger-print
        - solid/fire
        - solid/flag
        - solid/folder-arrow-down
        - solid/folder-minus
        - solid/folder-open
        - solid/folder-plus
        - solid/folder
        - solid/forward
        - solid/funnel
        - solid/gif
        - solid/gift-top
        - solid/gift
        - solid/globe-alt
        - solid/globe-americas
        - solid/globe-asia-australia
        - solid/globe-europe-africa
        - solid/hand-raised
        - solid/hand-thumb-down
        - solid/hand-thumb-up
        - solid/hashtag
        - solid/heart
        - solid/home-modern
        - solid/home
        - solid/identification
        - solid/inbox-arrow-down
        - solid/inbox-stack
        - solid/inbox
        - solid/information-circle
        - solid/key
        - solid/language
        - solid/lifebuoy
        - solid/light-bulb
        - solid/link
        - solid/list-bullet
        - solid/lock-closed
        - solid/lock-open
        - solid/magnifying-glass-circle
        - solid/magnifying-glass-minus
        - solid/magnifying-glass-plus
        - solid/magnifying-glass
        - solid/map-pin
        - solid/map
        - solid/megaphone
        - solid/microphone
        - solid/minus-circle
        - solid/minus-small
        - solid/minus
        - solid/moon
        - solid/musical-note
        - solid/newspaper
        - solid/no-symbol
        - solid/paint-brush
        - solid/paper-airplane
        - solid/paper-clip
        - solid/pause-circle
        - solid/pause
        - solid/pencil-square
        - solid/pencil
        - solid/phone-arrow-down-left
        - solid/phone-arrow-up-right
        - solid/phone-x-mark
        - solid/phone
        - solid/photo
        - solid/play-circle
        - solid/play-pause
        - solid/play
        - solid/plus-circle
        - solid/plus-small
        - solid/plus
        - solid/power
        - solid/presentation-chart-bar
        - solid/presentation-chart-line
        - solid/printer
        - solid/puzzle-piece
        - solid/qr-code
        - solid/question-mark-circle
        - solid/queue-list
        - solid/radio
        - solid/receipt-percent
        - solid/receipt-refund
        - solid/rectangle-group
        - solid/rectangle-stack
        - solid/rocket-launch
        - solid/rss
        - solid/scale
        - solid/scissors
        - solid/server-stack
        - solid/server
        - solid/share
        - solid/shield-check
        - solid/shield-exclamation
        - solid/shopping-bag
        - solid/shopping-cart
        - solid/signal-slash
        - solid/signal
        - solid/sparkles
        - solid/speaker-wave
        - solid/speaker-x-mark
        - solid/square-2-stack
        - solid/square-3-stack-3d
        - solid/squares-2x2
        - solid/squares-plus
        - solid/star
        - solid/stop-circle
        - solid/stop
        - solid/sun
        - solid/swatch
        - solid/table-cells
        - solid/tag
        - solid/ticket
        - solid/trash
        - solid/trophy
        - solid/truck
        - solid/tv
        - solid/user-circle
        - solid/user-group
        - solid/user-minus
        - solid/user-plus
        - solid/user
        - solid/users
        - solid/variable
        - solid/video-camera-slash
        - solid/video-camera
        - solid/view-columns
        - solid/viewfinder-circle
        - solid/wallet
        - solid/wifi
        - solid/window
        - solid/wrench-screwdriver
        - solid/wrench
        - solid/x-circle
        - solid/x-mark
        - outline/academic-cap
        - outline/adjustments-horizontal
        - outline/adjustments-vertical
        - outline/archive-box-arrow-down
        - outline/archive-box-x-mark
        - outline/archive-box
        - outline/arrow-down-circle
        - outline/arrow-down-left
        - outline/arrow-down-on-square-stack
        - outline/arrow-down-on-square
        - outline/arrow-down-right
        - outline/arrow-down-tray
        - outline/arrow-down
        - outline/arrow-left-circle
        - outline/arrow-left-on-rectangle
        - outline/arrow-left
        - outline/arrow-long-down
        - outline/arrow-long-left
        - outline/arrow-long-right
        - outline/arrow-long-up
        - outline/arrow-path-rounded-square
        - outline/arrow-path
        - outline/arrow-right-circle
        - outline/arrow-right-on-rectangle
        - outline/arrow-right
        - outline/arrow-small-down
        - outline/arrow-small-left
        - outline/arrow-small-right
        - outline/arrow-small-up
        - outline/arrow-top-right-on-square
        - outline/arrow-trending-down
        - outline/arrow-trending-up
        - outline/arrow-up-circle
        - outline/arrow-up-left
        - outline/arrow-up-on-square-stack
        - outline/arrow-up-on-square
        - outline/arrow-up-right
        - outline/arrow-up-tray
        - outline/arrow-up
        - outline/arrow-uturn-down
        - outline/arrow-uturn-left
        - outline/arrow-uturn-right
        - outline/arrow-uturn-up
        - outline/arrows-pointing-in
        - outline/arrows-pointing-out
        - outline/arrows-right-left
        - outline/arrows-up-down
        - outline/at-symbol
        - outline/backspace
        - outline/backward
        - outline/banknotes
        - outline/bars-2
        - outline/bars-3-bottom-left
        - outline/bars-3-bottom-right
        - outline/bars-3-center-left
        - outline/bars-3
        - outline/bars-4
        - outline/bars-arrow-down
        - outline/bars-arrow-up
        - outline/battery-0
        - outline/battery-100
        - outline/battery-50
        - outline/beaker
        - outline/bell-alert
        - outline/bell-slash
        - outline/bell-snooze
        - outline/bell
        - outline/bolt-slash
        - outline/bolt
        - outline/book-open
        - outline/bookmark-slash
        - outline/bookmark-square
        - outline/bookmark
        - outline/briefcase
        - outline/bug-ant
        - outline/building-library
        - outline/building-office-2
        - outline/building-office
        - outline/building-storefront
        - outline/cake
        - outline/calculator
        - outline/calendar-days
        - outline/calendar
        - outline/camera
        - outline/chart-bar-square
        - outline/chart-bar
        - outline/chart-pie
        - outline/chat-bubble-bottom-center-text
        - outline/chat-bubble-bottom-center
        - outline/chat-bubble-left-ellipsis
        - outline/chat-bubble-left-right
        - outline/chat-bubble-left
        - outline/chat-bubble-oval-left-ellipsis
        - outline/chat-bubble-oval-left
        - outline/check-badge
        - outline/check-circle
        - outline/check
        - outline/chevron-double-down
        - outline/chevron-double-left
        - outline/chevron-double-right
        - outline/chevron-double-up
        - outline/chevron-down
        - outline/chevron-left
        - outline/chevron-right
        - outline/chevron-up-down
        - outline/chevron-up
        - outline/circle-stack
        - outline/clipboard-document-check
        - outline/clipboard-document-list
        - outline/clipboard-document
        - outline/clipboard
        - outline/clock
        - outline/cloud-arrow-down
        - outline/cloud-arrow-up
        - outline/cloud
        - outline/code-bracket-square
        - outline/code-bracket
        - outline/cog-6-tooth
        - outline/cog-8-tooth
        - outline/cog
        - outline/command-line
        - outline/computer-desktop
        - outline/cpu-chip
        - outline/credit-card
        - outline/cube-transparent
        - outline/cube
        - outline/currency-bangladeshi
        - outline/currency-dollar
        - outline/currency-euro
        - outline/currency-pound
        - outline/currency-rupee
        - outline/currency-yen
        - outline/cursor-arrow-rays
        - outline/cursor-arrow-ripple
        - outline/device-phone-mobile
        - outline/device-tablet
        - outline/document-arrow-down
        - outline/document-arrow-up
        - outline/document-chart-bar
        - outline/document-check
        - outline/document-duplicate
        - outline/document-magnifying-glass
        - outline/document-minus
        - outline/document-plus
        - outline/document-text
        - outline/document
        - outline/ellipsis-horizontal-circle
        - outline/ellipsis-horizontal
        - outline/ellipsis-vertical
        - outline/envelope-open
        - outline/envelope
        - outline/exclamation-circle
        - outline/exclamation-triangle
        - outline/eye-dropper
        - outline/eye-slash
        - outline/eye
        - outline/face-frown
        - outline/face-smile
        - outline/film
        - outline/finger-print
        - outline/fire
        - outline/flag
        - outline/folder-arrow-down
        - outline/folder-minus
        - outline/folder-open
        - outline/folder-plus
        - outline/folder
        - outline/forward
        - outline/funnel
        - outline/gif
        - outline/gift-top
        - outline/gift
        - outline/globe-alt
        - outline/globe-americas
        - outline/globe-asia-australia
        - outline/globe-europe-africa
        - outline/hand-raised
        - outline/hand-thumb-down
        - outline/hand-thumb-up
        - outline/hashtag
        - outline/heart
        - outline/home-modern
        - outline/home
        - outline/identification
        - outline/inbox-arrow-down
        - outline/inbox-stack
        - outline/inbox
        - outline/information-circle
        - outline/key
        - outline/language
        - outline/lifebuoy
        - outline/light-bulb
        - outline/link
        - outline/list-bullet
        - outline/lock-closed
        - outline/lock-open
        - outline/magnifying-glass-circle
        - outline/magnifying-glass-minus
        - outline/magnifying-glass-mobile
        - outline/magnifying-glass-plus
        - outline/magnifying-glass
        - outline/map-pin
        - outline/map
        - outline/megaphone
        - outline/microphone
        - outline/minus-circle
        - outline/minus-small
        - outline/minus
        - outline/moon
        - outline/musical-note
        - outline/newspaper
        - outline/no-symbol
        - outline/paint-brush
        - outline/paper-airplane
        - outline/paper-clip
        - outline/pause-circle
        - outline/pause
        - outline/pencil-square
        - outline/pencil
        - outline/phone-arrow-down-left
        - outline/phone-arrow-up-right
        - outline/phone-x-mark
        - outline/phone
        - outline/photo
        - outline/play-circle
        - outline/play-pause
        - outline/play
        - outline/plus-circle
        - outline/plus-small
        - outline/plus
        - outline/power
        - outline/presentation-chart-bar
        - outline/presentation-chart-line
        - outline/printer
        - outline/puzzle-piece
        - outline/qr-code
        - outline/question-mark-circle
        - outline/queue-list
        - outline/radio
        - outline/receipt-percent
        - outline/receipt-refund
        - outline/rectangle-group
        - outline/rectangle-stack
        - outline/rocket-launch
        - outline/rss
        - outline/scale
        - outline/scissors
        - outline/server-stack
        - outline/server
        - outline/share
        - outline/shield-check
        - outline/shield-exclamation
        - outline/shopping-bag
        - outline/shopping-cart
        - outline/signal-slash
        - outline/signal
        - outline/sparkles
        - outline/speaker-wave
        - outline/speaker-x-mark
        - outline/square-2-stack
        - outline/square-3-stack-3d
        - outline/squares-2x2
        - outline/squares-plus
        - outline/star
        - outline/stop-circle
        - outline/stop
        - outline/sun
        - outline/swatch
        - outline/table-cells
        - outline/tag
        - outline/ticket
        - outline/trash
        - outline/trophy
        - outline/truck
        - outline/tv
        - outline/user-circle
        - outline/user-group
        - outline/user-minus
        - outline/user-plus
        - outline/user
        - outline/users
        - outline/variable
        - outline/video-camera-slash
        - outline/video-camera
        - outline/view-columns
        - outline/viewfinder-circle
        - outline/wallet
        - outline/wifi
        - outline/window
        - outline/wrench-screwdriver
        - outline/wrench
        - outline/x-circle
        - outline/x-mark
